### ISSUE TITLE
Not able display asset image from project

### ISSUE THREAD

**Issue by parteekpassi** [TheAlphamerc/empty_widget#5]
I am trying to use this (EmptyWidget) package in my application to display widget with text and image, when there is no data available to display to the user.

I am using the following code, I do not want to use packageImage but instead i want to use asset image from my project.
I have also noticed if i don't use packageImage parameter  or set it to null, 
I get Error: Null check operator used on a null value.

EmptyWidget(
              image: 'images/test.jpg',
              packageImage: PackageImage.Image_3,
              title: 'No Data Found',
            );
            
Even if I specify my image path using image attribute, It doesn't display image at all and I can't ignore packageImage attribute. I don't know if its a bug , it seems like that it is mandatory to use  packageImage attribute and use available images from it.
Could you please specify how could I use custom image from project and in some cases if i don't need to display image but text only, how could i do it.

Thanks,

**Comment by TheAlphamerc** [comment]
@parteekpassi thanks for let me know about this issue. Now I have fixed the issue and package `v0.0.4` is pushed on pub with this fix. Now you can use project assets or package image assets.

**Comment by parteekpassi** [comment]
@TheAlphamerc Thanks for fixing it. I have one more question is there any way that I can reduce the size of the image being displayed on this widget, Currently It occupies the whole screen with background circle. But I wanted to show small image size in the center of the screen not on the full screen, which looks weird. IS there a way I can control Image size and background circle.

**Comment by TheAlphamerc** [comment]
You can wrap the EmptyWidget in `container` or `SizedBox` widget and assign its width.
``` dart
Container(
        alignment: Alignment.center,
        width:300,
        height:300,
        child: EmptyWidget(
          image: null,
          packageImage: PackageImage.Image_1,
          title: 'No Notification',
          subTitle: 'No  notification available yet',
          titleTextStyle: TextStyle(
            fontSize: 22,
            color: Color(0xff9da9c7),
            fontWeight: FontWeight.w500,
          ),
          subtitleTextStyle: TextStyle(
            fontSize: 14,
            color: Color(0xffabb8d6),
          ),
        ),
      ),
    )
```

**Comment by parteekpassi** [comment]
> ```dart
> Container(
>         alignment: Alignment.center,
>         width:300,
>         height:300,
>         child: EmptyWidget(
>           image: null,
>           packageImage: PackageImage.Image_1,
>           title: 'No Notification',
>           subTitle: 'No  notification available yet',
>           titleTextStyle: TextStyle(
>             fontSize: 22,
>             color: Color(0xff9da9c7),
>             fontWeight: FontWeight.w500,
>           ),
>           subtitleTextStyle: TextStyle(
>             fontSize: 14,
>             color: Color(0xffabb8d6),
>           ),
>         ),
>       ),
>     )
> ```

**Comment by parteekpassi** [comment]
Thankyou

**Comment by parteekpassi** [comment]
Hi,

When I use empty widget package, it shows crystal ball in the background.
Is that possible that you can add additional attribute which controls if crystal ball needs to display or not.
By default you can set it true and if developer doesn't want it developer can set it to false something like that.
Currently it adds crystal ball in the background and I don't need it in my case. I just need image and text below.
![Screen Shot 2021-06-09 at 5 02 07 PM](https://user-images.githubusercontent.com/85317175/121429015-70a8c580-c944-11eb-8f57-f5b985a8c920.png)



Thank you,
Parteek

**Comment by TheAlphamerc** [comment]
@parteekpassi Yes, It can be possible. I'll implement this in new version of package.

**Comment by TheAlphamerc** [comment]
@parteekpassi  I have added a `hideBackgroundAnimation` property in widget. If you set it to `true` then background animation will no longer visible to you.

**Comment by parteekpassi** [comment]
Thank You for making a change and for a quick response, I really appreciate it. 
Now after setting hideBackgroundAnimation = true, i don't see this crystal ball background. But there seems to be a bug, image which i am using is flickering a bit, seems like it still have some animation component behind it.

**Comment by TheAlphamerc** [comment]
@parteekpassi The image have its own animation, which allows it to be remain in linear periodic motion.
